---
- hosts: all
  become: true

  tasks:
  - name: "apt update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "create www directory"
    file:
      path: /var/www/default
      state: directory
      mode: '0775'
      # owner: "{{ ansible_user }}"
      # group: "{{ ansible_user }}"

  - name: clear default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy website
    template:
      src: site/index.html
      dest: /var/www/default/index.html

  - name: copy nginx site.conf
    template:
      src: site/hello.conf
      dest: /etc/nginx/sites-enabled/default
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted